name: Dependabot auto-approve patch updates
on: pull_request

permissions:
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    strategy:
      matrix:
        dependencyStartsWith:
          - react-router
          - graphql
          - dayjs
          - autoprefixer
          - tailwindcss
          - '@glif/'
          - '@filecoin-station/core'
          - npm
          - ejs
          - '@electron/notarize'
          - braces
          - 'chart.js'
          - p-retry
          - nanoid
          - w3name
          - electron
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve a PR
        if: ${{startsWith(steps.metadata.outputs.dependency-names, matrix.dependencyStartsWith) && steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
