name: Dependabot auto-approve minor updates
on: pull_request

permissions:
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    strategy:
      matrix:
        dependencyStartsWith:
          - eslint
          - '@typescript-eslint/'
          - '@types/'
          - '@sentry/'
          - typescript
          - '@vitest/ui'
          - prettier
          - postcss
          - vite
          - '@testing-library/'
          - '@playwright/'
          - playwright
          - '@vitejs/plugin-react'
          - react-router
          - mocha
          - npm
          - jsdom
          - '@filecoin-station/spark-impact-evaluator'
          - '@radix-ui/'
          - undici
          - rollup
          - graphql
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve a PR
        if: ${{startsWith(steps.metadata.outputs.dependency-names, matrix.dependencyStartsWith) && (steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor')}}
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
